package com.bioinformatics.string_count;

/**
 * Bioinformatic program that can handle looking for
 * patterns in a DNA string.  This program can handle overlaps. 
 */



public class Main {

    public static void main(String[] args) {

       final String dna_string = "TCAACCTCGAATGCGAACCTCGCGACAACCTCGCAGCAACCTCGTAACCTCGAACCTCGTTATCAAAGAACCTCGTAACCTCGAACCTCGCTAACCTCGCCTGTAACCTCGACTATAAACCTCGCGTTCAACCTCGCAACCTCGTAACCTCGCAACCTCGAACCTCGGAACCTCGAAATAACCTCGCTAACCTCGAACCTCGTAACCTCGGCGAAAACCTCGTGAAACCTCGAAATAACCTCGTCCTCGTTCCGCAACGCAAACCTCGAACCTCGAAGCTCTCGCAACCTCGCCTGTTGCTCGAACCTCGAACTTAGGCCAACCTCGTCGTAACCTCGAACCTCGTTAAACCTCGAAATCCAACCTCGTCAACCTCGCAACCTCGCAACCTCGACTAACCTCGAACCTCGTCTTGAACTAGAACCTCGATAGTAACCTCGAACCTCGTACGGAACCTCGCAACCTCGAATCAACCTCGACTAACCTCGAACCTCGAACCTCGAGAAAGAACCTCGTAACCTCGTAACCTCGAACCTCGAACCTCGAAACCTCGGCAACCTCGAACCTCGACAACCTCGAGAACCTCGAACCTCGTAAGTGAGGGGTGCAACCTCGCAACCTCGTAGATGGTAACCTCGACGTGAACCTCGAAACCTCGCGCAAACCTCGGGATCGTAACCTCGAACCTCGGATGAACCTCGAACCTCGTAACCTCGAACCTCGAAACCTCGTTTAACCTCGAACCTCGGAACCTCGTTGAACCTCGAACCTCGGGAAACCTCGCAAAACTTAACCTCGAGGAAACCTCGGGACAACCTCGCGAAACCTCGTCGGGAACCTCGAACCTCGCAACCTCGAACCTCGCAGCAACCTCGCGAGGAACCTCGAACACAACCTCGATTTAACCTCGCGAACCTCGAACCTCGCAACCTCGAACCTCGAACCTCGCCAAACCTCGCCTAACCTCGAACCTCGAACCTCGAACCTCGAACCTCGGAACCTCGGTAACCTCG";
       final String pattern = "AACCTCGAA";

        int lastIndex = 0;
        int count = 0;

        while(lastIndex != -1){

            lastIndex = dna_string.indexOf(pattern, lastIndex);

            if(lastIndex != -1){
                count++;
                lastIndex++;

            }


        }
        System.out.println("Number of Occurences: " + count);



    }
}
